# Generated by Django 5.2.7 on 2025-10-12 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='club-img/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post-img/')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.club')),
            ],
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='city',
        ),
        migrations.RemoveField(
            model_name='traveltip',
            name='city',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='city',
        ),
        migrations.RemoveField(
            model_name='funfact',
            name='city',
        ),
        migrations.RemoveField(
            model_name='quickfact',
            name='city',
        ),
        migrations.RemoveField(
            model_name='transporttip',
            name='city',
        ),
        migrations.DeleteModel(
            name='CurrentCity',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RemoveField(
            model_name='neighborhoodtag',
            name='neighborhood',
        ),
        migrations.DeleteModel(
            name='Highlight',
        ),
        migrations.DeleteModel(
            name='TravelTip',
        ),
        migrations.DeleteModel(
            name='FunFact',
        ),
        migrations.DeleteModel(
            name='QuickFact',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='TransportTip',
        ),
        migrations.DeleteModel(
            name='Neighborhood',
        ),
        migrations.DeleteModel(
            name='NeighborhoodTag',
        ),
    ]
