# Generated by Django 5.2.7 on 2025-10-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_club_post_remove_highlight_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='club',
        ),
    ]
