# Generated by Django 5.2.7 on 2025-10-12 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_post_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.club'),
        ),
    ]
