# Generated by Django 5.2.7 on 2025-10-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_club_logo_convener_events_executives_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='logo',
        ),
    ]
