# Generated by Django 5.2.7 on 2025-10-13 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_club_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convener',
            name='mail',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Email must be in the format: username@uap-bd.edu', regex='^[a-zA-Z0-9._%+-]+@uap-bd\\.edu$')]),
        ),
        migrations.AlterField(
            model_name='executives',
            name='mail',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Email must be in the format: username@uap-bd.edu', regex='^[a-zA-Z0-9._%+-]+@uap-bd\\.edu$')]),
        ),
        migrations.AlterField(
            model_name='generalsecretary',
            name='mail',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Email must be in the format: username@uap-bd.edu', regex='^[a-zA-Z0-9._%+-]+@uap-bd\\.edu$')]),
        ),
        migrations.AlterField(
            model_name='president',
            name='mail',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Email must be in the format: username@uap-bd.edu', regex='^[a-zA-Z0-9._%+-]+@uap-bd\\.edu$')]),
        ),
        migrations.AlterField(
            model_name='treasurer',
            name='mail',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Email must be in the format: username@uap-bd.edu', regex='^[a-zA-Z0-9._%+-]+@uap-bd\\.edu$')]),
        ),
        migrations.AlterField(
            model_name='visepresident',
            name='mail',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Email must be in the format: username@uap-bd.edu', regex='^[a-zA-Z0-9._%+-]+@uap-bd\\.edu$')]),
        ),
    ]
