# Generated by Django 5.2.7 on 2025-10-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='registerUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
