# Generated by Django 5.2.7 on 2025-10-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_events_registerurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
