# Generated by Django 5.2.7 on 2025-10-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_events_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='location',
        ),
        migrations.RemoveField(
            model_name='events',
            name='registerUrl',
        ),
    ]
